### ISSUE TITLE
Black text - possible to fix?

### ISSUE THREAD

**Issue by scargill** [bonanitech/midnight-red#13]
Are you able to fix the black text in the node id in your own example - also some text in forms comes up black... bigtimer being an example - some text in the forms appears black.

**Comment by bonanitech** [comment]
@scargill thank you for raising this issue. I just changed the black text color in node id and in another few places. It will be available on the next release.

In the bigtimer forms, under node properties, you will need to add something in which I can apply the style. For example, add id in the <span> tags of the checkboxes at the end and also in the <p>Include/Exclude(...) tags.

I'll close this issue when I commit the changes, please raise a new one when bigtimer is updated so I can apply the dark theme on it.

**Comment by scargill** [comment]
And thank ~You for your quick response. I’ve realised that to some extent BigTimer shares the blame here as the text and checkboxes have no styling on them – but I freely admit that despite years of web programming, my CSS skills are not  up to it and the only style that would guarantee the white also messes up spacing (class=”form-row”). Hence your solution will be great for me. The checkboxes have IDs already but if you come up with some unique style name I can presumably add that..

 

For example here – I have text that has no style.. see the text in RED below..

 

 

                <div class="form-row">

                                <label  style="width:16%" for="node-input-d6"><i class="fa fa-calendar-o"></i> Day 6</label>

                                <input  style="width:26%" type="text" id="node-input-d6" value="0" placeholder="0">

                                <label  style="width:16%" for="node-input-w6"><i class="fa fa-calendar-o"></i> Week 6</label>

                                <input  style="width:26%" type="text" id="node-input-w6" value="0" placeholder="0">

                </div>

 

                <p>Exclude special days of the year (optional) day=1-31  month=1-12</p>

                <div class="form-row">

                                <label  style="width:16%" for="node-input-xday1"><i class="fa fa-calendar-o"></i> Day 1</label>

                                <input  style="width:26%" type="text" id="node-input-xday1" value="0" placeholder="0">

                                <label  style="width:16%" for="node-input-xmonth1"><i class="fa fa-calendar-o"></i> Month 1</label>

                                <input  style="width:26%" type="text" id="node-input-xmonth1" value="0" placeholder="0">

 

 

As for the checkboxes…

 

                <style>

                input[type=checkbox] { vertical-align:top; position:relative; bottom:1px; } 

                </style>

  

                <div>

    <span style="width: 50px; float: left; margin-left: 5px;"><input type="checkbox" id="node-input-sun" placeholder="sun" >Sun</span>

                                <span style="width: 50px; float: left; margin-left: 5px;"><input type="checkbox" id="node-input-mon" placeholder="mon" >Mon</span>

                                <span style="width: 50px; float: left; margin-left: 5px;"><input type="checkbox" id="node-input-tue" placeholder="tue" >Tue</span>

                                <span style="width: 50px; float: left; margin-left: 5px;"><input type="checkbox" id="node-input-wed" placeholder="wed" >Wed</span>

                                <span style="width: 50px; float: left; margin-left: 5px;"><input type="checkbox" id="node-input-thu" placeholder="thu" >Thu</span>

                                <span style="width: 50px; float: left; margin-left: 5px;"><input type="checkbox" id="node-input-fri" placeholder="fri" >Fri</span>

                                <span style="width: 50px; float: left; margin-left: 5px;"><input type="checkbox" id="node-input-sat" placeholder="sat" >Sat</span>

                </div>

                <br/>

 

Every attempt at adding the ”form-row” class ends up totally screwing up my spacing even with changes – so left as-is but with some style added (to eqch checkbox if need be) would work for BigTimer..

 

Regards

 

Pete

**Comment by scargill** [comment]
I just twigged that I can presumably add a unique style name of your choice to the one style of checkboxes I use for all. Just let me know and I’ll update – as long as I maintain total compatibility for those not using your theme..

 

This is at the top of my checkbox section…

 

<style>

                input[type=checkbox] { vertical-align:top; position:relative; bottom:1px; } 

</style>

**Comment by bonanitech** [comment]
I just want to make it clear that my suggestion is not the only (and probably not the best) solution to this issue. Maybe this [style guide](https://nodered.org/docs/creating-nodes/help-style-guide) brings you different ideas.

**Comment by scargill** [comment]
Don’t worry about BigTimer – all sorted. The changes you make may help others and that ID in your example – I remembered how to create and use classes and so all is well with bigTimer – not sure if I can include an image here but I’ll try.

 



 

Pete
