### ISSUE TITLE
Publish on npm

### ISSUE THREAD

**Issue by hobbyquaker** [bonanitech/midnight-red#16]
I think it would be useful to publish this package on npm, especially now after the breaking css class/id name changes that where introduced with Node-RED 1.0... I'm maintaining a project that bundles Node-RED into an special package for an "homematic" smart home central device and it would be very convenient and less error-prone for this usecase if I could include your theme in my build process through npm. 

What do you think? If you want me to I would create a PR with the boilerplate work and adapt the documentation.

**Comment by bonanitech** [comment]
@hobbyquaker that's an awesome idea, thanks for the suggestion. Will do it as soon as possible.

**Comment by bonanitech** [comment]
Trying to understand:

1. How to publish it
2. how to do it in a way that is as simple as possible for those who will use it

**Comment by bonanitech** [comment]
> 2. How to do it in a way that is as simple as possible for those who will use it

@hobbyquaker do you have suggestions on that?

**Comment by hobbyquaker** [comment]
hmm, don't really understand what the question is. I mean the theme files can be anywhere in the filesystem, you just have to put the correct path in the Node-RED settings. So it's just a question of documentation. If the User e.g. install it in `~/.node-red/node_modules/node-red-contrib-theme-midnight-red` the documentation should describe how to correctly reference that in the settings file.

**Comment by JamesMcCarthy79** [comment]
Love to see this on npm

**Comment by bonanitech** [comment]
There it is: https://www.npmjs.com/package/midnight-red

**Comment by colinl** [comment]
The readme doesn't appear to tell us how to install it using npm, or am I missing something?

**Comment by bonanitech** [comment]
I just published the theme at https://www.npmjs.com/package/node-red-contrib-theme-midnight-red

The code on this repo was migrated to https://github.com/bonanitech/node-red-contrib-theme-midnight-red.

I'm archiving this repo. If you still have questions please raise an issue in the new one.

Thank you all.
