### ISSUE TITLE
Adding relative to project path

### ISSUE THREAD

**Issue by bigdoods** [bonanitech/midnight-red#17]
I have added as an absolute path and it works great. Thank you! 

I would like to understand how to add this as a relative path to the project.

Currently, I am initialising node-red via `RED.init(server, settings);` and when I use the usual "./" prefix, I get the following Error: `path must be absolute or specify root to res.sendFile`

Thanks is advance

**Comment by bonanitech** [comment]
The [Node-RED forum](https://discourse.nodered.org/) would be the most appropriate place for this issue. It's a Node-RED configuration issue, not a problem in the theme itself.
